# Generated by Django 4.1.3 on 2022-12-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='second_type',
            options={'verbose_name': 'Second_Type', 'verbose_name_plural': 'Second_Types'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
    ]
