# Generated by Django 4.1.3 on 2022-12-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemons_attack_pokemons_defense_pokemons_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='sp_attack',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='sp_defense',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
