# Generated by Django 4.1.3 on 2022-12-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_pokemons_sp_attack_pokemons_sp_defense'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='total',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
