# Generated by Django 4.1.3 on 2022-12-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_pokemons_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='description',
        ),
    ]
