# Generated by Django 4.1.3 on 2022-12-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_remove_second_type_id_remove_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='legendary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='second_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.second_type'),
        ),
    ]
